import { TARGET } from "./SentenceTemplateCatalog.js";

const notationTemplates = () => [
  `The course materials introduced the notation “${TARGET}”.`,
  `The teacher explained how “${TARGET}” is used.`,
  `The notes included an example with “${TARGET}”.`,
];

export const SENTENCE_CONTEXT_OVERRIDES = new Map([
  ["balanced diet", [`A ${TARGET} includes foods from several groups.`, `The nutritionist recommended a ${TARGET}.`, `Regular exercise is easier to maintain with a ${TARGET}.`]],
  ["food pyramid", [`The diagram shows the ${TARGET}.`, `Students used the ${TARGET} to compare food groups.`, `The lesson explains each level of the ${TARGET}.`]],
  ["vitamin", [`The doctor recommended a ${TARGET}.`, `This fruit contains an important ${TARGET}.`, `The label lists each ${TARGET} in the supplement.`]],
  ["physician", [`The ${TARGET} examined the patient.`, `Please make an appointment with a ${TARGET}.`, `The ${TARGET} reviewed the test results.`]],
  ["nursery", [`The hospital has a ${TARGET} on the first floor.`, `She works in the children's ${TARGET}.`, `Parents can visit the ${TARGET} during the afternoon.`]],
  ["frequently", [`The buses run ${TARGET} throughout the day.`, `She ${TARGET} visits the library after class.`, `This question appears ${TARGET} in the survey.`]],
  ["sailing", [`They went ${TARGET} around the island.`, `The club offers beginner ${TARGET} lessons.`, `Strong winds cancelled the ${TARGET} trip.`]],
  ["get into debt", [`It is easy to ${TARGET} if you spend more than you earn.`, `Many people ${TARGET} when they rely too much on credit cards.`, `Students can ${TARGET} if they borrow more money than they can repay.`]],
  ["ex", [`My ${TARGET} moved to another city last year.`, `I ran into my ${TARGET} at a café yesterday.`, `She still speaks to her ${TARGET} occasionally.`]],
  ["return", [`Please ${TARGET} the book to the library by Friday.`, `I need to ${TARGET} this shirt to the store.`, `They will ${TARGET} home after the trip.`]],
  ["include", [`Please ${TARGET} your phone number on the form.`, `The price does not ${TARGET} breakfast.`, `The report should ${TARGET} a short summary.`]],
  ["relationship (between/with)", notationTemplates()],
  ["relate (to)", notationTemplates()],
  ["(eating) disorder", notationTemplates()],
  ["(achieve a) balance", notationTemplates()],
  ["achieve (a goal)", notationTemplates()],
  ["miss (an opportunity)", notationTemplates()],
  ["set (a goal)", notationTemplates()],
  ["take part (in)", notationTemplates()],
  ["field (of study)", notationTemplates()],
  ["adopt (an approach)", notationTemplates()],
  ["learn (about)", notationTemplates()],
  ["take (a course)", notationTemplates()],
  ["refer (to)", notationTemplates()],
  ["prior (to)", notationTemplates()],
  ["crop(s)", notationTemplates()],
  ["laptop (computer)", notationTemplates()],
  ["(have a) monopoly", notationTemplates()],
  ["exhaust (fumes)", notationTemplates()],
  ["in danger (of)", notationTemplates()],
  ["unleaded (petrol)", notationTemplates()],
  ["invest (in)", notationTemplates()],
  ["petty (crime)", notationTemplates()],
  ["abide (by)", notationTemplates()],
  ["be (held) responsible for", notationTemplates()],
]);
