import { TARGET } from "./SentenceTemplateCatalog.js";

export const CURATED_TERM_TEMPLATES = new Map([
  ["surname", [`My ${TARGET} is Bayat.`, `Please write your ${TARGET} exactly as it appears on your passport.`, `The receptionist asked me to spell my ${TARGET}.`]],
  ["first name", [`My ${TARGET} is Mohammad.`, `What is your ${TARGET}?`, `Please enter your ${TARGET} on the registration form.`]],
  ["middle name", [`I do not use a ${TARGET} on official forms.`, `Please enter your ${TARGET} if you have one.`, `The application has a separate box for a ${TARGET}.`]],
  ["full name", [`Please state your ${TARGET} for the recording.`, `I wrote my ${TARGET} at the top of the form.`, `The receptionist checked my ${TARGET} against my passport.`]],
  ["initials", [`Please write your ${TARGET} in the two small boxes.`, `His ${TARGET} appear beside his signature.`, `The form asks for both your name and your ${TARGET}.`]],
  ["title", [`Please select your ${TARGET}, such as Mr, Ms or Dr.`, `The registration form has a drop-down list for your ${TARGET}.`, `She entered “Dr” as her ${TARGET}.`]],
  ["age", [`The application form asks for your ${TARGET}.`, `You must be over eighteen years of ${TARGET} to apply.`, `The receptionist confirmed my ${TARGET} before making the booking.`]],
  ["date of birth", [`Please enter your ${TARGET} in day-month-year order.`, `The receptionist checked my ${TARGET} against my passport.`, `The form requires both your name and your ${TARGET}.`]],
  ["nationality", [`The application asks for your ${TARGET}.`, `She wrote “Canadian” in the box marked ${TARGET}.`, `The receptionist confirmed my ${TARGET} during the call.`]],
  ["address", [`Please write your current ${TARGET} on the form.`, `The parcel was delivered to the wrong ${TARGET}.`, `The receptionist repeated my ${TARGET} to check it was correct.`]],
  ["postcode", [`Please enter the ${TARGET} for your home address.`, `The receptionist asked me to repeat my ${TARGET}.`, `The delivery form will not continue without a valid ${TARGET}.`]],
  ["postal code", [`Please enter the ${TARGET} for your home address.`, `The receptionist asked me to repeat my ${TARGET}.`, `The delivery form will not continue without a valid ${TARGET}.`]],
  ["email address", [`Please enter your ${TARGET} in lowercase letters.`, `The confirmation was sent to my ${TARGET}.`, `The receptionist asked me to spell my ${TARGET}.`]],
  ["telephone number", [`Please leave a ${TARGET} where we can contact you.`, `The receptionist repeated my ${TARGET} to confirm every digit.`, `I wrote my home ${TARGET} on the application.`]],
  ["mobile number", [`Please enter your ${TARGET} in the contact section.`, `The confirmation message was sent to my ${TARGET}.`, `The receptionist checked each digit of my ${TARGET}.`]],
  ["emergency contact", [`Please name one ${TARGET} on the registration form.`, `My sister is listed as my ${TARGET}.`, `The form asks for an ${TARGET} and a telephone number.`]],
  ["membership number", [`Please quote your ${TARGET} when you call us.`, `My ${TARGET} is printed on the front of the card.`, `The receptionist used my ${TARGET} to find the account.`]],
  ["registration number", [`Please enter your ${TARGET} at the top of the form.`, `The receptionist used my ${TARGET} to find the booking.`, `Your ${TARGET} appears in the confirmation email.`]],
  ["reference number", [`Please quote your ${TARGET} when you contact customer service.`, `The ${TARGET} appears at the top of the letter.`, `The adviser used my ${TARGET} to locate the application.`]],
  ["passport number", [`Please enter your ${TARGET} exactly as it appears in the document.`, `The booking form requires a valid ${TARGET}.`, `The agent checked my ${TARGET} before issuing the ticket.`]],
  ["identification", [`Please bring photographic ${TARGET} to the appointment.`, `The receptionist asked to see my ${TARGET}.`, `A passport can be used as proof of ${TARGET}.`]],
  ["signature", [`Please put your ${TARGET} at the bottom of the form.`, `The bank compared the ${TARGET} with the one on file.`, `The document is not valid without your ${TARGET}.`]],
  ["marital status", [`The application includes a question about your ${TARGET}.`, `Please select your ${TARGET} from the list.`, `The interviewer did not ask about my ${TARGET}.`]],
  ["weekdays", [`The library stays open later on ${TARGET}.`, `Traffic is usually heavier on ${TARGET}.`, `The course runs only on ${TARGET}.`]],
  ["weekend", [`We are planning a short trip this ${TARGET}.`, `The museum is busiest at the ${TARGET}.`, `I usually review my notes over the ${TARGET}.`]],
  ["three times", [`I listened to the recording ${TARGET}.`, `The phone rang ${TARGET} before anyone answered.`, `She checked the spelling ${TARGET}.`]],
  ["three times a week", [`She attends the language class ${TARGET}.`, `The pool is cleaned ${TARGET}.`, `I practise pronunciation ${TARGET}.`]],
  ["a gap year", [`He plans to take ${TARGET} before university.`, `She travelled abroad during ${TARGET}.`, `Taking ${TARGET} gave him useful work experience.`]],
  ["part-time", [`She works ${TARGET} while studying.`, `I am looking for a ${TARGET} course.`, `He changed from full-time to ${TARGET} work.`]],
  ["midday", [`The tour begins at ${TARGET}.`, `We stopped for lunch around ${TARGET}.`, `The sun is strongest at ${TARGET}.`]],
  ["midnight", [`The last train leaves at ${TARGET}.`, `The booking system closes at ${TARGET}.`, `We arrived just before ${TARGET}.`]],
  ["in advance", [`You must pay ${TARGET} to confirm the booking.`, `Please reserve your seat ${TARGET}.`, `The hotel asks guests to book ${TARGET}.`]],
  ["withdraw", [`You can ${TARGET} cash from this machine.`, `Customers may ${TARGET} up to five hundred pounds a day.`, `She went to the bank to ${TARGET} some money.`]],
  ["available immediately", [`The flat is ${TARGET}.`, `The agent confirmed that the room was ${TARGET}.`, `This furnished studio is ${TARGET}.`]],
  ["strongly recommended", [`The guided tour is ${TARGET}.`, `Advance booking is ${TARGET} during summer.`, `This safety course is ${TARGET} for new staff.`]],
  ["poor quality", [`The customer said the product was of ${TARGET}.`, `We returned the item because it was ${TARGET}.`, `Several reviews complained about the ${TARGET}.`]],
  ["pregnant", [`The nurse confirmed that the patient was ${TARGET}.`, `She told the doctor that she was ${TARGET}.`, `The form asks whether the patient is ${TARGET}.`]],
  ["northern", [`The ${TARGET} entrance is closed today.`, `They explored the ${TARGET} part of the island.`, `The storm moved across the ${TARGET} coast.`]],
  ["alone", [`She completed the journey ${TARGET}.`, `The child should not wait ${TARGET}.`, `He prefers to study ${TARGET}.`]],
  ["bilingual", [`The receptionist is ${TARGET} and speaks English and French.`, `The school offers a ${TARGET} programme.`, `Growing up ${TARGET} helped her communicate abroad.`]],
  ["trilingual", [`The guide is ${TARGET} and speaks three languages.`, `They hired a ${TARGET} receptionist.`, `Becoming ${TARGET} took years of practice.`]],
  ["polyglot", [`The tour guide is a ${TARGET}.`, `As a ${TARGET}, she can work in several languages.`, `The conference hired a ${TARGET} to help international guests.`]],
  ["linguistics", [`She studies ${TARGET} at university.`, `The lecture introduced a theory from ${TARGET}.`, `His research in ${TARGET} focuses on bilingual children.`]],
  ["pottery", [`She makes bowls in her ${TARGET} class.`, `The museum displays traditional ${TARGET}.`, `I joined a weekend course in ${TARGET}.`]],
  ["team", [`Our ${TARGET} trains every Tuesday.`, `Each ${TARGET} has six players.`, `She works well as part of a ${TARGET}.`]],
  ["walking", [`Regular ${TARGET} can improve your fitness.`, `We joined a guided ${TARGET} tour.`, `She prefers ${TARGET} to driving short distances.`]],
  ["art", [`The gallery displays modern ${TARGET}.`, `She studies ${TARGET} at college.`, `The festival brings ${TARGET} into public spaces.`]],
  ["app", [`I downloaded the ${TARGET} to my phone.`, `The travel ${TARGET} works without an internet connection.`, `Open the ${TARGET} to check your booking.`]],
  ["wifi", [`The hotel offers free ${TARGET}.`, `Please ask reception for the ${TARGET} password.`, `The ${TARGET} signal is stronger near the lounge.`]],
  ["cash", [`Please pay in ${TARGET}.`, `I withdrew some ${TARGET} from the bank.`, `The clerk counted the ${TARGET} carefully.`]],
  ["yoga", [`She attends a ${TARGET} class every Tuesday.`, `Regular ${TARGET} helps her relax after work.`, `The centre offers beginner ${TARGET} in the mornings.`]],
  ["tai-chi", [`He practises ${TARGET} in the park.`, `The centre runs a weekly ${TARGET} class.`, `Regular ${TARGET} can improve balance.`]],
  ["keep-fit", [`She joined a ${TARGET} class at the sports centre.`, `The ${TARGET} session starts at six o'clock.`, `This ${TARGET} programme is suitable for beginners.`]],
  ["salad bar", [`The café has a fresh ${TARGET}.`, `Lunch is served beside the ${TARGET}.`, `The hotel added a ${TARGET} to the dining room.`]],
  ["outdoor activities", [`The camp offers several ${TARGET}.`, `Children can choose from different ${TARGET}.`, `Bad weather may cancel the ${TARGET}.`]],
  ["leisure time", [`She reads during her ${TARGET}.`, `The survey asks how people use their ${TARGET}.`, `Exercise takes up most of his ${TARGET}.`]],
  ["meal", [`Breakfast is the first ${TARGET} of the day.`, `The price includes one hot ${TARGET}.`, `We shared a ${TARGET} after the lecture.`]],
  ["cetacean", [`A whale is a ${TARGET}.`, `The researcher identified the animal as a ${TARGET}.`, `Every ${TARGET} must surface to breathe.`]],
  ["clinic", [`The ${TARGET} opens at eight o'clock.`, `She works at a dental ${TARGET}.`, `Please call the ${TARGET} to make an appointment.`]],
  ["tourist", [`The ${TARGET} asked for a city map.`, `Every ${TARGET} receives a visitor guide.`, `A lost ${TARGET} approached the information desk.`]],
  ["shop", [`The ${TARGET} closes at six o'clock.`, `I bought the jacket from a local ${TARGET}.`, `The new ${TARGET} is beside the station.`]],
  ["safety", [`During the tour, ${TARGET} is the main priority.`, `All staff complete annual ${TARGET} training.`, `The briefing begins with basic ${TARGET} rules.`]],
  ["cognitive", [`The study measured ${TARGET} development.`, `Researchers tested several ${TARGET} skills.`, `The lecture focused on ${TARGET} processes.`]],
  ["electronic", [`The ticket is stored in ${TARGET} form.`, `We use an ${TARGET} device to record the data.`, `The library provides access to ${TARGET} journals.`]],
  ["licence", [`You need a driving ${TARGET} to hire a car.`, `Her ${TARGET} expires next month.`, `Please bring your ${TARGET} to the registration desk.`]],
  ["analysis", [`The ${TARGET} revealed a clear pattern.`, `Our ${TARGET} is based on survey data.`, `The report includes a detailed ${TARGET}.`]],
]);

export const VERB_TEMPLATES = new Map([
  ["give a talk", [`She will ${TARGET} on climate change.`, `The tutor asked each student to ${TARGET}.`, `I have been invited to ${TARGET} at the conference.`]],
  ["fail", [`A student may ${TARGET} the exam without enough preparation.`, `I was afraid I might ${TARGET} the driving test.`, `Students who ${TARGET} can take the course again.`]],
  ["retake", [`You can ${TARGET} the test next month.`, `She decided to ${TARGET} the exam in June.`, `Students must pay a fee to ${TARGET} this module.`]],
  ["evaluate", [`The panel will ${TARGET} every proposal.`, `Students learn to ${TARGET} different sources.`, `We need more data to ${TARGET} the programme.`]],
  ["train", [`The athletes ${TARGET} every morning.`, `New staff ${TARGET} with an experienced supervisor.`, `You should ${TARGET} regularly before the race.`]],
  ["develop", [`The team will ${TARGET} a new plan.`, `Children ${TARGET} language skills through practice.`, `Researchers hope to ${TARGET} a safer method.`]],
  ["collect", [`Please ${TARGET} the forms from reception.`, `Researchers ${TARGET} data from every participant.`, `We need to ${TARGET} the tickets before leaving.`]],
  ["supervise", [`A tutor will ${TARGET} the group.`, `Senior staff ${TARGET} new employees.`, `She was asked to ${TARGET} the experiment.`]],
  ["mark", [`Please ${TARGET} your answer clearly.`, `Tutors ${TARGET} the assignments each week.`, `Use a pencil to ${TARGET} the correct location.`]],
  ["exhibit", [`Local artists ${TARGET} their work at the museum.`, `The gallery will ${TARGET} three new sculptures.`, `Students can ${TARGET} their final projects.`]],
  ["hire a car", [`We plan to ${TARGET} at the airport.`, `You need a driving licence to ${TARGET}.`, `They decided to ${TARGET} for the weekend.`]],
  ["cook", [`I usually ${TARGET} dinner at home.`, `The chef will ${TARGET} the vegetables slowly.`, `Students learn to ${TARGET} healthy meals.`]],
  ["grill", [`We will ${TARGET} the vegetables outside.`, `The chef likes to ${TARGET} fresh fish.`, `Please ${TARGET} the bread for two minutes.`]],
  ["bake", [`She plans to ${TARGET} a loaf of bread.`, `We ${TARGET} the potatoes in the oven.`, `Please ${TARGET} the cake for forty minutes.`]],
  ["boil", [`Please ${TARGET} the water before drinking it.`, `We ${TARGET} the eggs for six minutes.`, `The recipe says to ${TARGET} the rice first.`]],
  ["fry", [`The chef will ${TARGET} the onions in a little oil.`, `Do not ${TARGET} the fish for too long.`, `We usually ${TARGET} these vegetables quickly.`]],
  ["roast", [`They ${TARGET} the vegetables with herbs.`, `The chef will ${TARGET} the chicken slowly.`, `Please ${TARGET} the nuts before serving them.`]],
  ["steam", [`We ${TARGET} the vegetables to keep them fresh.`, `The recipe says to ${TARGET} the fish.`, `You can ${TARGET} the rice in this cooker.`]],
  ["turn", [`Please ${TARGET} left at the traffic lights.`, `You should ${TARGET} right after the bridge.`, `You need to ${TARGET} at the next corner.`]],
  ["move", [`Please ${TARGET} towards the main entrance.`, `We need to ${TARGET} the table beside the window.`, `Please ${TARGET} carefully across the wet floor.`]],
  ["continue", [`Please ${TARGET} along the footpath.`, `You should ${TARGET} straight ahead for two hundred metres.`, `You can ${TARGET} after the short break.`]],
  ["walk", [`Please ${TARGET} past the library.`, `You can ${TARGET} along the river until you reach the bridge.`, `We usually ${TARGET} to the station.`]],
  ["cross", [`Please ${TARGET} the road at the traffic lights.`, `You should ${TARGET} the bridge and turn right.`, `Do not ${TARGET} until the signal changes.`]],
  ["pass", [`You will ${TARGET} the museum on your left.`, `Please ${TARGET} the information desk before turning.`, `The bus will ${TARGET} the central station.`]],
  ["start", [`The tour will ${TARGET} at nine o'clock.`, `Please ${TARGET} at the main entrance.`, `We can ${TARGET} the meeting after lunch.`]],
  ["finish", [`The lecture should ${TARGET} by midday.`, `Please ${TARGET} the form before leaving.`, `We expect to ${TARGET} the project this week.`]],
  ["end", [`The path will ${TARGET} beside the lake.`, `The course will ${TARGET} in December.`, `Please ${TARGET} the presentation with a conclusion.`]],
  ["stop", [`The bus will ${TARGET} outside the museum.`, `Please ${TARGET} at the reception desk.`, `You should ${TARGET} if the alarm sounds.`]],
  ["exit", [`Please ${TARGET} through the rear door.`, `Passengers must ${TARGET} the station on the left.`, `Use the stairs to ${TARGET} the building.`]],
  ["agree", [`I ${TARGET} with the final proposal.`, `Most students ${TARGET} that the course is useful.`, `The two groups finally ${TARGET} on a solution.`]],
  ["disagree", [`I ${TARGET} with that conclusion.`, `Some researchers ${TARGET} about the cause.`, `The committee may ${TARGET} with the recommendation.`]],
  ["recycle", [`Please ${TARGET} paper and glass.`, `The factory can ${TARGET} most of its waste.`, `We should ${TARGET} these containers instead of throwing them away.`]],
  ["fulfil", [`The course will ${TARGET} the entry requirement.`, `Applicants must ${TARGET} every condition.`, `The programme aims to ${TARGET} the needs of local students.`]],
  ["analyse", [`Researchers will ${TARGET} the survey data.`, `Students learn to ${TARGET} complex results.`, `We need to ${TARGET} the evidence carefully.`]],
]);

export const DIRECTION_TEMPLATES = new Map([
  ["north", [`The car park is ${TARGET} of the main building.`, `The river flows ${TARGET} from the village.`, `Drive ${TARGET} until you reach the bridge.`]],
  ["south", [`The station is ${TARGET} of the city centre.`, `The path continues ${TARGET} along the coast.`, `Travel ${TARGET} for about five kilometres.`]],
  ["east", [`The museum is ${TARGET} of the park.`, `The road runs ${TARGET} from the junction.`, `Head ${TARGET} after leaving the station.`]],
  ["west", [`The village lies ${TARGET} of the river.`, `The route continues ${TARGET} across the valley.`, `Drive ${TARGET} until the road ends.`]],
  ["northeast", [`The lake is ${TARGET} of the campsite.`, `The path heads ${TARGET} through the forest.`, `Travel ${TARGET} from the crossroads.`]],
  ["northwest", [`The farm is ${TARGET} of the town.`, `The storm moved ${TARGET} during the night.`, `Follow the road ${TARGET} from the bridge.`]],
  ["southeast", [`The airport is ${TARGET} of the city.`, `The railway line runs ${TARGET}.`, `Continue ${TARGET} after the roundabout.`]],
  ["southwest", [`The beach lies ${TARGET} of the hotel.`, `The track turns ${TARGET} near the hill.`, `Drive ${TARGET} from the main junction.`]],
  ["right", [`Turn ${TARGET} at the corner.`, `The ticket office is on your ${TARGET}.`, `Keep to the ${TARGET} side of the path.`]],
  ["left", [`Turn ${TARGET} after the bridge.`, `The library is on your ${TARGET}.`, `Keep to the ${TARGET} side of the corridor.`]],
  ["straight ahead", [`Walk ${TARGET} until you reach the bank.`, `The main entrance is ${TARGET}.`, `Continue ${TARGET} for two hundred metres.`]],
  ["across from", [`The café is ${TARGET} the library.`, `The bus stop is ${TARGET} the main entrance.`, `You will see the bank ${TARGET} the park.`]],
  ["between", [`The café is ${TARGET} the bank and the library.`, `The lift is ${TARGET} the two staircases.`, `The garden lies ${TARGET} the museum and the river.`]],
  ["beside", [`The car park is ${TARGET} the station.`, `A bench stands ${TARGET} the footpath.`, `The café is ${TARGET} the main entrance.`]],
  ["diagonal", [`Draw a ${TARGET} line across the square.`, `The path follows a ${TARGET} route through the park.`, `A ${TARGET} stripe crosses the sign.`]],
  ["opposite", [`The hotel is ${TARGET} the station.`, `The lift is ${TARGET} the reception desk.`, `Sit on the bench ${TARGET} the entrance.`]],
  ["adjacent to", [`The laboratory is ${TARGET} the library.`, `The car park is ${TARGET} the sports centre.`, `Our room is ${TARGET} the lift.`]],
  ["near", [`The hotel is ${TARGET} the beach.`, `There is a bus stop ${TARGET} the entrance.`, `We met ${TARGET} the central station.`]],
  ["past", [`Walk ${TARGET} the bank and turn left.`, `The bus goes ${TARGET} the museum.`, `Continue ${TARGET} the information desk.`]],
  ["before", [`Turn left just ${TARGET} the bridge.`, `The café is the last building ${TARGET} the junction.`, `Please arrive ten minutes ${TARGET} the tour starts.`]],
  ["after", [`Turn right ${TARGET} the traffic lights.`, `The library is the first building ${TARGET} the bridge.`, `We can meet ${TARGET} the lecture.`]],
]);
