-- Vocora database schema is migration-driven.
--
-- Do not add tables or columns directly to this file. Add an immutable,
-- numbered migration under back/database/migrations/ and run:
--
--   npm run db:setup
--
-- `db:setup` records each migration checksum in `schema_migrations`, seeds the
-- built-in IELTS collection, and migrates legacy JSON learning states into the
-- normalized persistence model.
